### ISSUE TITLE
Pub/Sub stops after first message has been received.

### ISSUE THREAD

**Issue by janflyborg** [nickdesaulniers/node-nanomsg#156] opened 2016-06-04 10:39 UTC
I am absolutely new to nanomsg, so I might be doing something really stupid, but I can't get this simple PUBSUB example to work:

```javascript
var nano = require('nanomsg');
var addr = 'tcp://127.0.0.1:7789'

var pub = nano.socket('pub');
pub.bind(addr);

var sub1 = nano.socket('sub');
sub1.on('data', function (buf) {
  console.log('sub1:' + String(buf));
});
sub1.chan(['topic1'])
sub1.connect(addr);

var sub2 = nano.socket('sub');
sub2.on('data', function (buf) {
  console.log('sub2:' + String(buf));
});
sub2.chan(['topic2'])
sub2.connect(addr);

setInterval(function () {
    console.log('sending');
    pub.send("topic1 Hello from nanomsg!");
    console.log('sent');
}, 1000);
```
Running this gives me:

```
sending
sent
sub1:topic1 Hello from nanomsg!
```

And then there is nothing more (even if the node process does not exit). I would expect the setInterval to do this repeatedly, but after the first message has been received there is nothing more.

Any ideas? I have tried this on nodejs 5.11.0 on my Mac and on 6.2.0 on an Ubuntu machine.

**Comment by yoshuawuyts** [comment] 2016-06-04 20:51
Ah, it appears if `sub2` is removed, it works again - digging further.

**Comment by yoshuawuyts** [comment] 2016-06-04 20:52
Ah alright, so `sub1` starts blocking when a message of `topic2` is sent - digging further.

**Comment by yoshuawuyts** [comment] 2016-06-04 20:57
`inproc://` is the same as `tcp://`

**Comment by yoshuawuyts** [comment] 2016-06-04 20:59
[This test](https://github.com/nickdesaulniers/node-nanomsg/blob/399ad1188c1518ee44ca75ae1bc131006cbe4991/test/chan.js#L105-L142) makes it appear as if it should work, hmmmmm

**Comment by yoshuawuyts** [comment] 2016-06-04 21:02
Validated, this code works:
```js
var nano = require('nanomsg')
const assert = require('assert')

var pub = nano.socket('pub')
var sub = nano.socket('sub')

var msgs = 0
var addr = 'inproc://prefixed'

pub.bind(addr)
sub.connect(addr)

sub.chan(['foo', 'hello'])

sub.on('data', function (buf) {
  var msg = String(buf)

  if (++msgs < 2) {
    assert.equal(msg, 'foo world')
    console.log(msg)
  } else {
    assert.equal(msg, 'hello world')
    console.log(msg)
    sub.close()
    pub.close()
  }
})

var msg1 = 'foo world'
var msg2 = 'bar world'
var msg3 = 'hi world'
var msg4 = 'hello world'

pub.send(msg1)
pub.send(msg2)
pub.send(msg3)
process.nextTick(function () {
  pub.send(msg4)
})
```

**Comment by yoshuawuyts** [comment] 2016-06-04 21:03
Still works using `tcp://` - digginggggggg

**Comment by yoshuawuyts** [comment] 2016-06-04 21:12
Alright, it's also not the case that in a `nextTick` errors are being handled differently. This works fine:
```js
process.nextTick(function () {
  pub.send(msg3)
  process.nextTick(function () {
    pub.send(msg4)
  })
})
```

**Comment by reqshark** [comment] 2016-06-04 21:29
wait, you have to understand that the way libnanomsg handles adding and removing channel subscriptions involves some extra latency before the channels are set/unset

**Comment by yoshuawuyts** [comment] 2016-06-04 21:30
Alright, think I found a bug. In the above example this works:
```js
sub.chan(['foo', 'hello'])
```
But this breaks:
```js
sub.chan(['foo'])
```

**Comment by yoshuawuyts** [comment] 2016-06-04 21:32
@reqshark yeah, I know - `setInterval()`'s first call doesn't run on the same tick I believe, so `nanomsg` should have had enough time to setup all channels. Or is my thinking off here? Afaic we're not setting + unsetting channels all the time; just filtering messages on subscribers right?

**Comment by reqshark** [comment] 2016-06-04 21:34
tick ordering doesn't matter at all to libnanomsg. 

are you saying setting 1 channel doesn't work?

**Comment by yoshuawuyts** [comment] 2016-06-04 21:35
Yes. Repro:
```js
var nano = require('nanomsg')
var pub = nano.socket('pub');
var sub = nano.socket('sub');

var msgs = 0;
var msg1 = 'foo world';
var msg2 = 'bar world';
var msg3 = 'hi world';
var msg4 = 'hello world';
var addr = 'inproc://prefixed';

pub.bind(addr);
sub.connect(addr);

sub.chan(['foo']);

sub.on('data', function (buf) {

  var msg = String(buf);

  if(++msgs < 2){
  } else {
    sub.close();
    pub.close();
  }
});

pub.send(msg1);
pub.send(msg2);
pub.send(msg3);
process.nextTick(function(){
  pub.send(msg4);
})
```

**Comment by reqshark** [comment] 2016-06-04 21:38
k thanks, yea i'm not a fan of this code: https://github.com/nickdesaulniers/node-nanomsg/blob/master/lib/index.js#L440

We need to fix this

**Comment by yoshuawuyts** [comment] 2016-06-04 22:30
More error cases:
```js
var nano = require('nanomsg')

var addr = 'inproc://prefixed'

var pub = nano.socket('pub')
pub.bind(addr)

var msg1 = 'foo world'
var msg2 = 'bar world'

var sub1 = nano.socket('sub')
sub1.connect(addr)
sub1.chan(['foo', 'bar'])
sub1.on('data', (buf) => console.log(String(buf)))

setTimeout(function () {
  pub.send(msg1)
  pub.send(msg2)
}, 1000)
```
```js
var nano = require('nanomsg')

var addr = 'inproc://prefixed'

var pub = nano.socket('pub')
pub.bind(addr)

var msg1 = 'foo world'
var msg2 = 'bar world'
var msg3 = 'beep world'
var msg4 = 'boop world'

var sub1 = nano.socket('sub')
sub1.connect(addr)
sub1.chan(['foo', 'bar'])
sub1.on('data', (buf) => console.log(String(buf)))

var sub2 = nano.socket('sub')
sub2.connect(addr)
sub2.chan(['beep', 'boop'])
sub2.on('data', (buf) => console.log(String(buf)))

setTimeout(function () {
  pub.send(msg1)
  pub.send(msg2)
  pub.send(msg3)
  pub.send(msg4)
}, 1000)
```

**Comment by janflyborg** [comment] 2016-06-05 09:25
Thanks for looking into this. I thought I had missunderstod the whole concept.

@yoshuawuyts: Your last two error cases actually seem to work on my setup.

The first one gives me
```
foo world
bar world
```

and the last one gives me:
```
foo world
beep world
bar world
boop world
```

**Comment by yoshuawuyts** [comment] 2016-06-05 10:02
Oh hah I did, `setTimeout` not `setInterval` - oops :grin: - `setInterval` doesn't work tho

**Comment by reqshark** [comment] 2016-06-05 10:02
@janflyborg the last seems to work for me on osx w/ same exact results, but not so for the penultimate

**Comment by reqshark** [comment] 2016-06-05 10:35
oh this is cool actually. this proves the thing works as intended, which is not always easy to test

I'll explain how the logic set up in that [2nd to last test](https://gist.github.com/reqshark/92f5d3bc936f663d6cbe2c32e82ee806) helps demonstrate working channels:
• there's only one `foo` msg sent in 2nd to last test case
• we pre-increment msgs until more than one `foo` msg is recv'd before closing sockets

when i adjust the code in the 2nd to last case to check for the only msg w/ foo, it works as expected:

```js
  if(msg === 'foo world'){
    console.log('dude, why did i label this a bug?')
    sub.close();
    pub.close();
  }
```

**Comment by yoshuawuyts** [comment] 2016-06-05 10:54
I don't get this :|

**Comment by janflyborg** [comment] 2016-06-05 10:55
Me neither...

**Comment by reqshark** [comment] 2016-06-05 11:04
my explanation only debunks one additional test case we thought demonstrated the bug

we still have not dealt with the original bug case of this issue, so lets return to the original case `topic1` socket and `topic2` socket.. 

why when removing sub2 (`topic2`) socket code messages from topic1 interval appear?

**Comment by reqshark** [comment] 2016-06-05 11:11
```js
var nano = require('nanomsg');
var addr = 'tcp://127.0.0.1:7789'

var pub = nano.socket('pub');
pub.bind(addr);

var sub1 = nano.socket('sub');
sub1.on('data', function (buf) {
  console.log('sub1:' + String(buf));
});
sub1.chan(['topic1'])
sub1.connect(addr);

//var sub2 = nano.socket('sub');
//sub2.on('data', function (buf) {
//  console.log('sub2:' + String(buf));
//});
//sub2.chan(['topic2'])
//sub2.connect(addr);

setInterval(function () {
    console.log('sending');
    pub.send("topic1 Hello from nanomsg!");
    console.log('sent');
}, 1000);
```
this breaks when adding sub2 commented out code.. why does adding another arbitrary subscription socket matter here? this is what needs to be fixed.

**Comment by reqshark** [comment] 2016-06-05 11:19
@janflyborg thanks for bringing this to light. my advice for now is do your own filtering protocol on top of default nanomsg subscription until this is resolved.

**Comment by janflyborg** [comment] 2016-06-05 11:28
OK. I see, Thanks for the help everyone. In the service I'm planning to use nanomsg for, I only have a handful of nodes, so receiving all messages and doing my own filtering should not give much of a performance impact (I guess).

**Comment by reqshark** [comment] 2016-06-05 14:30
you can get nanomsg performance with a separate process for those subscription sockets/nodes

the bug seems to arise while simultaneous subscription sockets maintain distinct channel topics pointed to the same publisher while running in the same script/process.  In practice, this doesn't seem likely, since, in this case, a single subscription socket should be registered to multiple topics

**Comment by janflyborg** [comment] 2016-06-05 16:43
OK. In that case i won't affect me at all, since I will use this for load-balancing between processes.

**Comment by alimousazy** [comment] 2016-06-27 10:01
I have the same issue, when the first sub get the message. The other one stop receiving any messages or survey query.

**Comment by alimousazy** [comment] 2016-06-27 10:49
Changing the socket to non blocking solved the problem for me

  var msg = nn.Recv(this.binding, nn.NN_DONTWAIT);

@reqshark

**Comment by reqshark** [comment] 2016-06-27 14:00
@alimousazy, could you send a PR?

**Comment by alimousazy** [comment] 2016-06-27 17:09
@reqshark Here is a pull request https://github.com/nickdesaulniers/node-nanomsg/pull/160, thanks for helping out.

**Closed** 2016-06-27 17:19 UTC
Labels: bug
